/**
 * Created by slashhuang on 16/8/9.
 */
function MyPlugin() {}

MyPlugin.prototype.apply = function(compiler) {
    compiler.plugin('emit', function(compilation, callback) {

        compilation.modules.forEach(function (_module) {
           console.log(_module.chunks[0].toString())
        });
        /**
         *  Explore each chunk (build output):
         */
        compilation.chunks.forEach(function(chunk) {
            /**
             *  Explore each module within the chunk (built inputs)
             */

            // console.log(chunk.modules)
            chunk.modules && chunk.modules.forEach(function(module) {
                /**
                 * Explore each source file path that was included into the module:
                 */

                module.fileDependencies && module.fileDependencies.forEach(function(filepath) {
                    /**
                     *  we've learned a lot about the source structure now...
                     */
                });
            });

            /**
             * Explore each asset filename generated by the chunk:
             */
            chunk.files.forEach(function(filename) {
                /**
                 * Get the asset source for each file generated by the chunk:
                 */
                var source = compilation.assets[filename].source();
                // console.log(source);
            });
        });

        callback();
    });
};

module.exports = MyPlugin;